Use "python" instead of "python2.7" in unix_build.sh
When running `./unix_build.sh`:

```
(env3) root@5a694b7dd154:/wbia/pydarknet# ./unix_build.sh
Removing old build
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named utool
Creating new build
```

We don't have anything installed in python2.7 causing this utool import error.
The command seems to run fine using python 3.6 in the wbia docker container.